name: Task
description: Create Task
labels: [task]
body:
- type: input
  attributes:
    label: Story
    description: What story is this task part of?
    placeholder: '#123'
- type: textarea
  attributes:
    label: Description
    description: Describe the task
